language: python

python:
  - "3.9"

services:
  - docker

before_install:
  - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
  - sudo apk add --update --no-cache jpeg-dev mariadb-connector-c-dev
  - sudo apk add --update --no-cache --virtual .tmp-build-deps gcc libc-dev linux-headers musl-dev zlib zlib-dev
  - sudo pip install -r requirements.txt
  - sudo apk del .tmp-build-deps
  - sudo mkdir -p /vol/web/media
  - sudo mkdir -p /vol/web/static
  - sudo adduser -D user
  - sudo RUN chown -R user:user /vol/
  - sudo RUN chmod -R 755 /vol/web
  - sudo USER user

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py wait_for_db && python manage.py test && flake8"

notifications:
  email: false
