version: "3.8"

services:
  gcartapp:
    build:
      context: .
      dockerfile: gcartapp/gcartapp.dockerfile
    volumes:
      - ./gcartapp:/gcartapp
      - ./gcartapp/container/media:/vol/web/media
      - ./gcartapp/container/static:/vol/web/static
    ports:
      - 8000:8000
    command: >
      sh -c "
      python manage.py wait_for_db &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    # gunicorn -w 2 -b 0.0.0.0:8000 core.wsgi:application --reload"
    # gunicorn -w 2 -b 0.0.0.0:8000 --chdir ./gcartapp  core.wsgi:application --reload"
    depends_on:
      - db
      - redis
    links:
      - redis

  db:
    image: mysql:8.0
    volumes:
      - ./data:/var/lib/mysql
    env_file:
      - db/db.env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
    depends_on:
      - db
    ports:
      - 8080:80

  redis:
    image: redis:6
    container_name: redis

  celery:
    build:
      context: .
      dockerfile: gcartapp/gcartapp.dockerfile
    volumes:
      - ./gcartapp:/gcartapp
    container_name: cl01
    command: celery -A core worker -l info
    links:
      - redis

networks:
  default:
    external:
      name: box-net
