# Generated by Django 3.2.6 on 2021-09-01 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_variation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="variation",
            options={"ordering": ["variation_value"]},
        ),
    ]
