# Generated by Django 3.2.6 on 2021-09-15 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name_plural': 'Product Gallery'},
        ),
    ]
