# Generated by Django 3.2.6 on 2021-09-01 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_variation_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variations",
                to="store.product",
            ),
        ),
    ]
