# Generated by Django 3.2.6 on 2021-09-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_note",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
