# Generated by Django 3.2.6 on 2021-09-03 14:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_auto_20210903_1412"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
