# Generated by Django 3.2.6 on 2021-09-03 17:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
