# Generated by Django 3.2.6 on 2021-09-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_payment_signature"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="signature_code",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
