# Generated by Django 3.2.6 on 2021-09-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_variation_product"),
        ("orders", "0006_payment_signature_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="variation",
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="variations",
            field=models.ManyToManyField(blank=True, to="store.Variation"),
        ),
    ]
