# Generated by Django 3.2.6 on 2021-09-04 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_auto_20210904_1316"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orders.payment",
            ),
        ),
    ]
