from django.urls import path

from .views import (
    RegisterView,
    LoginView,
    LogoutView,
    ActivatePageView,
    DashboardView,
    ForgotPasswordView,
    ResetPasswordValidateView,
    ResetPasswordView,
    MyOrdersView,
    EditProfileView,
)

urlpatterns = [
    path(
        "dashboard/",
        DashboardView.as_view(),
        name="dashboard",
    ),
    path(
        "register/",
        RegisterView.as_view(),
        name="register",
    ),
    path(
        "login/",
        LoginView.as_view(),
        name="login",
    ),
    path(
        "logout/",
        LogoutView.as_view(),
        name="logout",
    ),
    path(
        "activate/<uidb64>/<token>/",
        ActivatePageView.as_view(),
        name="activate",
    ),
    path(
        "forgotpassword/",
        ForgotPasswordView.as_view(),
        name="forgotpassword",
    ),
    path(
        "",
        DashboardView.as_view(),
        name="",
    ),
    path(
        "resetpassword_validate/<uidb64>/<token>/",
        ResetPasswordValidateView.as_view(),
        name="resetpassword_validate",
    ),
    path(
        "reset_password/",
        ResetPasswordView.as_view(),
        name="reset_password",
    ),
    path(
        "my_orders/",
        MyOrdersView.as_view(),
        name="my_orders",
    ),
    path(
        "edit_profile/",
        EditProfileView.as_view(),
        name="edit_profile",
    ),
]
