# Generated by Django 3.2.6 on 2021-08-31 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="quanity",
            new_name="quantity",
        ),
    ]
