# Generated by Django 3.2.6 on 2021-09-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_variation_product"),
        ("cart", "0002_rename_quanity_cartitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="variations",
            field=models.ManyToManyField(blank=True, to="store.Variation"),
        ),
    ]
